Repository Landry333/Big-Owl, pull requests merged in 2020-11, with the labels that each got.

#115 #111 Auth repository creation
  app/src/main/java/com/example/bigowlapp/activity/SignUpPageActivity.java
  app/src/main/java/com/example/bigowlapp/repository/AuthRepository.java
  app/src/main/java/com/example/bigowlapp/repository/Repository.java
Labels: technical story

#155 [#56] UI testing for SupervisedGroupListActivity
  app/src/androidTest/java/com/example/bigowlapp/activity/SupervisedGroupListActivityTest.java
  app/src/main/java/com/example/bigowlapp/activity/SupervisedGroupListActivity.java
  app/src/main/java/com/example/bigowlapp/viewModel/SupervisedGroupListViewModel.java
Labels: pull request

#156 #65 code quality implementations
  .github/workflows/build.yaml
  .github/workflows/reviewdog.yaml
  app/build.gradle
  app/src/main/res/values/strings.xml
  build.gradle
Labels: pull request

#161 #43 fixing parsing for contact number to be searched in DB and on SMS
  app/src/main/java/com/example/bigowlapp/activity/SearchContactsByPhone.java
  app/src/main/java/com/example/bigowlapp/activity/SearchContactsToSupervise.java
  app/src/main/java/com/example/bigowlapp/activity/SendSmsInvitationActivity.java
  app/src/main/java/com/example/bigowlapp/activity/ViewAnotherUserActivity.java
Labels: pull request

#167 #159 templates for issues
  .github/ISSUE_TEMPLATE/acceptance_test.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/ISSUE_TEMPLATE/technical_story.md
  .github/ISSUE_TEMPLATE/tests.md
  .github/ISSUE_TEMPLATE/user_story.md
  .github/pull_request_template.md
Labels: pull request, repository
