Repository Landry333/Big-Owl, pull requests merged in 2021-04, with the labels that each got.

#243 #82 Constants for database fields refactor
  app/src/androidTest/java/com/example/bigowlapp/activity/SupervisedGroupListActivityTest.java
  app/src/androidTest/java/com/example/bigowlapp/activity/SupervisedGroupPageActivityTest.java
  app/src/main/java/com/example/bigowlapp/activity/SearchContactsByPhone.java
  app/src/main/java/com/example/bigowlapp/activity/SearchContactsToSupervise.java
  app/src/main/java/com/example/bigowlapp/activity/SendingRequestToSuperviseActivity.java
  app/src/main/java/com/example/bigowlapp/activity/SupervisedGroupListActivity.java
  app/src/main/java/com/example/bigowlapp/fragments/SupervisionResponseFragment.java
  app/src/main/java/com/example/bigowlapp/model/Attendance.java
  app/src/main/java/com/example/bigowlapp/model/AuthByPhoneNumberFailure.java
  app/src/main/java/com/example/bigowlapp/model/Group.java
  app/src/main/java/com/example/bigowlapp/model/Notification.java
  app/src/main/java/com/example/bigowlapp/model/Schedule.java
  app/src/main/java/com/example/bigowlapp/model/ScheduleRequest.java
  app/src/main/java/com/example/bigowlapp/model/SupervisionRequest.java
  app/src/main/java/com/example/bigowlapp/model/User.java
  app/src/main/java/com/example/bigowlapp/repository/AuthRepository.java
  app/src/main/java/com/example/bigowlapp/repository/GroupRepository.java
  app/src/main/java/com/example/bigowlapp/repository/NotificationRepository.java
  app/src/main/java/com/example/bigowlapp/repository/ScheduleRepository.java
  app/src/main/java/com/example/bigowlapp/repository/UserRepository.java
  app/src/main/java/com/example/bigowlapp/utils/IsSmsSenderACurrentEventSupervisor.java
  app/src/main/java/com/example/bigowlapp/viewModel/MonitoringGroupPageViewModel.java
  app/src/main/java/com/example/bigowlapp/viewModel/SetScheduleViewModel.java
  app/src/main/java/com/example/bigowlapp/viewModel/SupervisedGroupListViewModel.java
  app/src/test/java/com/example/bigowlapp/viewModel/SetScheduleViewModelTest.java
Labels: pull request

#262 #24 missed schedule notif
  app/build.gradle
  app/src/main/java/com/example/bigowlapp/activity/SearchContactsByPhone.java
  app/src/main/java/com/example/bigowlapp/activity/SendingRequestToSuperviseActivity.java
  app/src/main/java/com/example/bigowlapp/service/LocationTrackingExpiredAlarmReceiver.java
  app/src/main/java/com/example/bigowlapp/service/MemberScheduleAlarmReceiver.java
  app/src/main/java/com/example/bigowlapp/utils/DateTimeFormatter.java
  app/src/main/java/com/example/bigowlapp/utils/IntentConstants.java
  app/src/main/java/com/example/bigowlapp/utils/LocationTrackingExpiredAlarmManager.java
  app/src/main/java/com/example/bigowlapp/utils/MemberScheduleAlarmManager.java
  app/src/main/java/com/example/bigowlapp/utils/ScheduledLocationTrackingManager.java
Labels: pull request

#264 #25 schedule report for supervisor
  app/src/androidTest/java/com/example/bigowlapp/activity/HomePageActivityTest.java
  app/src/androidTest/java/com/example/bigowlapp/activity/ScheduleReportActivityTest.java
  app/src/androidTest/java/com/example/bigowlapp/activity/SupervisedGroupPageActivityTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/bigowlapp/activity/ListOfScheduleActivity.java
  app/src/main/java/com/example/bigowlapp/activity/MonitoringGroupPageActivity.java
  app/src/main/java/com/example/bigowlapp/activity/ScheduleReportActivity.java
  app/src/main/java/com/example/bigowlapp/adapter/ScheduleReportMembersAdapter.java
  app/src/main/java/com/example/bigowlapp/model/Attendance.java
  app/src/main/java/com/example/bigowlapp/model/Schedule.java
  app/src/main/java/com/example/bigowlapp/model/UserScheduleResponse.java
  app/src/main/java/com/example/bigowlapp/repository/ScheduleRepository.java
  app/src/main/java/com/example/bigowlapp/repository/UserRepository.java
  app/src/main/java/com/example/bigowlapp/utils/GeoLocationFormatter.java
  app/src/main/java/com/example/bigowlapp/viewModel/ScheduleListViewModel.java
  app/src/main/java/com/example/bigowlapp/viewModel/ScheduleReportViewModel.java
  app/src/main/res/layout/activity_monitoring_group_page.xml
  app/src/main/res/layout/activity_schedule_report.xml
  app/src/main/res/layout/fragment_schedule_report_members.xml
  app/src/main/res/values/strings.xml
Labels: pull request

#271 #13 authentication with fingerprint and user phone number detection after login, to access user account
  app/build.gradle
  app/src/androidTest/java/com/example/bigowlapp/activity/EditProfileViewTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/bigowlapp/activity/EditProfileActivity.java
  app/src/main/java/com/example/bigowlapp/activity/FingerprintAuthenticationActivity.java
  app/src/main/java/com/example/bigowlapp/activity/HomePageActivity.java
  app/src/main/java/com/example/bigowlapp/activity/LoginPageActivity.java
  app/src/main/java/com/example/bigowlapp/activity/SignUpPageActivity.java
  app/src/main/java/com/example/bigowlapp/model/User.java
  app/src/main/java/com/example/bigowlapp/utils/SupervisorSmsListener.java
  app/src/main/java/com/example/bigowlapp/viewModel/EditProfileViewModel.java
  app/src/main/java/com/example/bigowlapp/viewModel/HomePageViewModel.java
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_fingerprint_authenticaton.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/example/bigowlapp/viewModel/EditProfileViewModelTest.java
Labels: pull request

#276 #273 bug fix contacts black screen
  app/src/androidTest/java/com/example/bigowlapp/activity/SignUpPageActivityTest.java
  app/src/main/java/com/example/bigowlapp/activity/EditProfileActivity.java
  app/src/main/java/com/example/bigowlapp/activity/FingerprintAuthenticationActivity.java
  app/src/main/java/com/example/bigowlapp/activity/LoginPageActivity.java
  app/src/main/java/com/example/bigowlapp/activity/SearchContactsByPhone.java
  app/src/main/java/com/example/bigowlapp/activity/SearchContactsToSupervise.java
  app/src/main/java/com/example/bigowlapp/activity/SendingRequestToSuperviseActivity.java
  app/src/main/java/com/example/bigowlapp/activity/SignUpPageActivity.java
  app/src/main/java/com/example/bigowlapp/repository/exception/EmptyFieldException.java
  app/src/main/java/com/example/bigowlapp/utils/AuthenticatorByPhoneNumber.java
  app/src/main/java/com/example/bigowlapp/utils/PhoneNumberFormatter.java
  app/src/main/java/com/example/bigowlapp/utils/SupervisorSmsListener.java
  app/src/test/java/com/example/bigowlapp/utils/PhoneNumberFormatterTest.java
Labels: pull request

#280 #278 279 bug fixes
  app/src/main/java/com/example/bigowlapp/viewModel/MonitoringGroupPageViewModel.java
  app/src/main/java/com/example/bigowlapp/viewModel/SignUpViewModel.java
Labels: pull request

#274 Us 71 notifications
  app/src/androidTest/java/com/example/bigowlapp/activity/LoginPageActivityTest.java
  app/src/main/java/com/example/bigowlapp/activity/LoginPageActivity.java
  app/src/main/java/com/example/bigowlapp/activity/SendSmsInvitationActivity.java
  app/src/main/java/com/example/bigowlapp/activity/SignUpPageActivity.java
  app/src/main/java/com/example/bigowlapp/adapter/NotificationAdapter.java
  app/src/main/java/com/example/bigowlapp/model/Notification.java
  app/src/main/java/com/example/bigowlapp/model/SmsInvitationRequest.java
  app/src/main/java/com/example/bigowlapp/repository/RepositoryFacade.java
  app/src/main/java/com/example/bigowlapp/repository/SmsInvitationRepository.java
  app/src/main/java/com/example/bigowlapp/utils/AuthFailureNotificationListener.java
  app/src/main/java/com/example/bigowlapp/utils/NotificationListenerManager.java
  app/src/main/java/com/example/bigowlapp/viewModel/SignUpViewModel.java
Labels: pull request

#282 PR-281 -
  app/src/main/java/com/example/bigowlapp/utils/NotificationListenerManager.java
Labels: pull request

#285 #73 Fixing message when canceling request and editing other text
  app/src/main/java/com/example/bigowlapp/activity/SendingRequestToSuperviseActivity.java
  app/src/main/res/layout/activity_add_users.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/values/strings.xml
Labels: pull request

#283 #32 notification on new time location schedule
  app/src/main/java/com/example/bigowlapp/fragments/NotificationListFragment.java
  app/src/main/java/com/example/bigowlapp/model/Notification.java
  app/src/main/java/com/example/bigowlapp/model/ReceiveScheduleNotification.java
  app/src/main/java/com/example/bigowlapp/repository/NotificationRepository.java
  app/src/main/java/com/example/bigowlapp/repository/Repository.java
  app/src/main/java/com/example/bigowlapp/utils/NotificationListenerManager.java
  app/src/main/java/com/example/bigowlapp/viewModel/SetScheduleViewModel.java
  app/src/test/java/com/example/bigowlapp/viewModel/SetScheduleViewModelTest.java
Labels: pull request

#306 #307 Fixed delayed notification bug
  app/src/main/java/com/example/bigowlapp/utils/LocationTrackingExpiredAlarmManager.java
Labels: pull request

#308 # 25 fix tests
  app/src/androidTest/java/com/example/bigowlapp/activity/ScheduleReportActivityTest.java
  app/src/main/java/com/example/bigowlapp/activity/ScheduleReportActivity.java
  app/src/main/java/com/example/bigowlapp/utils/GeoLocationFormatter.java
Labels: pull request, testing

#313 #311 bug with notification listener fix
  app/src/main/java/com/example/bigowlapp/activity/BigOwlActivity.java
  app/src/main/java/com/example/bigowlapp/repository/AuthRepository.java
  app/src/main/java/com/example/bigowlapp/utils/NotificationListenerManager.java
  app/src/test/java/com/example/bigowlapp/utils/NotificationListenerManagerTest.java
Labels: bug, pull request

#314 #13 Test for fingerprint authentication activity after login
  app/src/androidTest/java/com/example/bigowlapp/activity/FingerprintAuthenticationActivityTest.java
  app/src/main/java/com/example/bigowlapp/activity/FingerprintAuthenticationActivity.java
  app/src/main/java/com/example/bigowlapp/model/User.java
Labels: pull request, testing
